### PR TITLE
 Fix missing location data for Rich Computer Center

### LINKED ISSUE #37: Cannot locate Rich Computer Center
**Describe the bug**
I found that the Map cannot locate "Rich-Computer Center".
I think it is because OSCAR uses the name "Rich-Computer Center" while Map uses the name "Rich Computer Center", without dash ("-") (But I am not sure about this)

**To Reproduce**
Steps to reproduce the behavior. Example:
1. Add PUBP 6502 Course of Spring 2025
2. Go to Map and select Tuesday
3. Then you can see the alert at up-left side, "Undetermined PUBP 6502"

**Expected behavior**
The location should be determined and displayed on the Map.

**Screenshots**

Image

**Additional context**

### PR DESCRIPTION
**Pull request by raptor1820**
Resolves #37
### Issue
Lat and long coordinates for the Rich Computer Center were missing in the parser which prevented it from rendering correctly on the map.

### Changes
- Transferred issue from website to crawler-v2
- Added the missing coordinates to `src/steps/parse.ts`
- Verified that the RCC appears correctly on the map

### Images
image

### CODE REVIEW

File: src/steps/parse.ts [hunk 1]
```diff
@@ -80,6 +80,8 @@ const courseLocations = new Map([
   ["Savant", new Location(33.772075, -84.395277)],
   ["ISyE Main", new Location(33.775178, -84.401879)],
   ["Fourth Street Houses", new Location(33.775381, -84.391451)],
+  ["Rich-Computer Center", new Location(33.77535159008218, -84.39513500282604)],
```
Comment (afazio1) [inline src/steps/parse.ts:83]: Are both of these needed for the location to render on the map?

Comment (raptor1820) [reply src/steps/parse.ts:83]: No, only the first one is needed since OSCAR lists them with a dash(-). I added the second one as a contingency in case OSCAR starts listing it without the dash.

Comment (uma-anand) [reply src/steps/parse.ts:83]: Let's keep it minimal for now and reduce bloat. We can add it later if that becomes an issue.
